#' Cut nb_sim data by calendar date
#'
#' @param data Data generated by [nb_sim()].
#' @param ... Additional arguments passed to methods.
#' @param cut_date Calendar time (relative to trial start) at which to censor follow-up.
#'
#' @return A data frame with one row per subject randomized prior to `cut_date` containing
#'   the truncated follow-up time (`tte`) and total number of observed events (`events`).
#'
#' @examples
#' enroll_rate <- data.frame(rate = 20 / (5 / 12), duration = 5 / 12)
#' fail_rate <- data.frame(treatment = c("Control", "Experimental"), rate = c(0.5, 0.3))
#' dropout_rate <- data.frame(
#'   treatment = c("Control", "Experimental"),
#'   rate = c(0.1, 0.05), duration = c(100, 100)
#' )
#' sim <- nb_sim(enroll_rate, fail_rate, dropout_rate, max_followup = 2, n = 20)
#' cut_data_by_date(sim, cut_date = 1)
#' @export
cut_data_by_date <- function(data, cut_date, ...) {
  UseMethod("cut_data_by_date")
}

#' @export
cut_data_by_date.default <- function(data, cut_date, ...) {
  stop("No cut_data_by_date() method for objects of class ", class(data)[1], call. = FALSE)
}

#' @export
cut_data_by_date.nb_sim_data <- function(data, cut_date, ...) {
  if (is.null(cut_date) || length(cut_date) != 1L || !is.finite(cut_date)) {
    stop("cut_date must be a single finite numeric value", call. = FALSE)
  }

  dt <- data.table::as.data.table(data)
  dt[, calendar_time := enroll_time + tte]
  dt <- dt[enroll_time < cut_date]
  if (nrow(dt) == 0) {
    return(data.frame(
      id = integer(0), treatment = character(0), enroll_time = numeric(0),
      tte = numeric(0), events = integer(0)
    ))
  }

  agg <- dt[,
    {
      followup_limit <- cut_date - first(enroll_time)
      followup_limit <- max(followup_limit, 0)
      tte_in_window <- tte[calendar_time <= cut_date]
      max_tte_in_window <- if (length(tte_in_window)) max(tte_in_window) else 0
      overall_max_tte <- max(tte)
      max_tte <- min(overall_max_tte, followup_limit)
      max_tte <- max(max_tte, max_tte_in_window)
      list(
        treatment = first(treatment),
        enroll_time = first(enroll_time),
        tte = max_tte,
        events = as.integer(sum(event == 1 & calendar_time <= cut_date))
      )
    },
    by = id
  ]

  data.table::setorder(agg, id)
  out <- as.data.frame(agg)
  out
}
